name: UI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Node environment
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci
        working-directory: ui

      - name: Run Biome Check
        run: npm run ci
        working-directory: ui

      - name: Run Vitest Tests
        run: npm run test:coverage
        working-directory: ui

      - name: Build UI
        run: npm run build
        working-directory: ui

      - name: Check static files uncommitted
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "There are uncommitted changes."
            git diff
            exit 1
          else
            echo "No uncommitted changes found."
          fi
