name: Docker Build

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Start JupyterHub
      run: |
        jupyterhub -f jupyterhub_config.py &
        docker compose build
        docker compose up -d
        # Give some time to start
        sleep 10
        docker compose logs

      working-directory: docker

    - name: Build JHub Image
      run: |
        docker build -t jhub -f Dockerfile.jhub .
        sleep 5
      working-directory: docker
