name: Lint

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Setup Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.12'

    - name: Install ruff
      run: |
        pip install ruff

    - name: Lint with ruff
      run: |
        ruff check .
