name: Release

on: [release, workflow_dispatch]

env:
  HATCH_INDEX_USER: __token__
  HATCH_INDEX_AUTH: ${{ secrets.HATCH_INDEX_AUTH }}

jobs:
  release:
    name: Release jhub-apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases/tag/v7.0.0
        uses: actions/checkout@v7

      - name: Setup Python
        # https://github.com/actions/setup-python/releases/tag/v6.3.0
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install uv
        # https://github.com/astral-sh/setup-uv/releases/tag/v8.2.0
        uses: astral-sh/setup-uv@v8.2.0

      - name: Install dependencies
        run: uv sync

      - name: Hatch Build
        run: uv run hatch build

      - name: Hatch Publish
        run: uv run hatch publish -n
