name: Release

on: [release, workflow_dispatch]

env:
  HATCH_INDEX_USER: __token__
  HATCH_INDEX_AUTH: ${{ secrets.HATCH_INDEX_AUTH }}

jobs:
  release:
    name: Release jhub-apps
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases/tag/v5.0.0
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Setup Python
        # https://github.com/mamba-org/setup-micromamba/releases/tag/v2.0.6
        uses: mamba-org/setup-micromamba@7f29b8b80078b1b601dfa018b0f7425c587c63bb
        with:
          environment-file: environment-dev.yml
          create-args: >-
            python=${{ matrix.python-version }}
            -c conda-forge

      - name: Install uv
        # https://github.com/astral-sh/setup-uv/releases/tag/v6.8.0
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e

      - name: Install dependencies
        run: uv sync

      - name: Hatch Build
        run: hatch build

      - name: Hatch Publish
        run: hatch publish -n
