name: Release

on: [release, workflow_dispatch]

env:
  HATCH_INDEX_USER: __token__
  HATCH_INDEX_AUTH: ${{ secrets.HATCH_INDEX_AUTH }}

jobs:
  release:
    name: Release jhub-apps
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Python
        uses: mamba-org/setup-micromamba@v1.8.0
        with:
          environment-file: environment-dev.yml
          create-args: >-
            python=${{ matrix.python-version }}
            -c conda-forge

      - name: Install Hatch
        run: pip install hatch

      - name: Hatch Build
        run: hatch build

      - name: Hatch Publish
        run: hatch publish -n
