name: Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
        test_type:
          - tests_unit
        jupyterhub:
          - "==4.1.5"
          - ">=5.0.0"
    steps:
    # https://github.com/actions/checkout/releases/tag/v5.0.0
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

    - name: Setup Python
      # https://github.com/mamba-org/setup-micromamba/releases/tag/v2.0.6
      uses: mamba-org/setup-micromamba@7f29b8b80078b1b601dfa018b0f7425c587c63bb
      with:
        environment-file: environment-dev.yml
        create-args: >-
          python=${{ matrix.python-version }}
          -c conda-forge

    - name: Install uv
      # https://github.com/astral-sh/setup-uv/releases/tag/v6.8.0
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e

    - name: Install dependencies
      run: |
        if [ "${{ matrix.jupyterhub }}" = "==4.1.5" ]; then
          uv sync --group test-jupyterhub-4 --extra dev
        else
          uv sync --group test-jupyterhub-5 --extra dev
        fi

    - name: conda list
      run: conda list

    - name: pip freeze
      run: pip freeze

    - name: Run Tests
      run: |
        GROUP_FLAG=""
        if [ "${{ matrix.jupyterhub }}" = "==4.1.5" ]; then
          GROUP_FLAG="--group test-jupyterhub-4"
        else
          GROUP_FLAG="--group test-jupyterhub-5"
        fi
        uv run $GROUP_FLAG --extra dev pytest jhub_apps/tests/${{ matrix.test_type }} -vvv -s --log-cli-level=INFO
