name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
        test_type:
          - tests
        jupyterhub_version:
          - "jupyterhub>4.1"
          - "git+https://github.com/jupyterhub/jupyterhub.git@ca6032381aa137f03cb9349265fa74ed5e4c5c19"
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup Python
      uses: mamba-org/setup-micromamba@v1.8.1
      with:
        environment-file: environment-dev.yml
        create-args: >-
          python=${{ matrix.python-version }}
          -c conda-forge

    - name: Install JupyterHub
      run: |
        pip install ${{ matrix.jupyterhub }}

    - name: conda list
      run: conda list

    - name: Install JHub Apps
      run: |
        pip install .

    - name: Run Tests
      run: |
        pytest jhub_apps/${{ matrix.test_type }} -vvv -s
