name: Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
        test_type:
          - tests_unit
        jupyterhub:
          - "==4.1.5"
          - ">=5.0.0"
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup Python
      uses: mamba-org/setup-micromamba@v1.8.1
      with:
        environment-file: environment-dev.yml
        create-args: >-
          python=${{ matrix.python-version }}
          -c conda-forge

    - name: Install JHub Apps
      run: |
        pip install .

    - name: Install JupyterHub
      run: |
        pip install jupyterhub${{ matrix.jupyterhub }}

    - name: conda list
      run: conda list

    - name: pip freeze
      run: pip freeze

    - name: Run Tests
      run: |
        pytest jhub_apps/tests/${{ matrix.test_type }} -vvv -s
